<a href="https://colab.research.google.com/github/Vaibhavbhor404/workshops/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
myList=[[1,2,3],[4,5,6],[7,8,9]]
npArray=np.array(myList)
print(npArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.random.rand(5))

[0.64591851 0.18279054 0.85872658 0.41311139 0.60782171]


In [4]:
print(np.random.rand(4,4))

[[0.38487202 0.05988662 0.89253661 0.93161646]
 [0.23443482 0.35223529 0.16978132 0.28993574]
 [0.00609172 0.20187754 0.32817192 0.87623739]
 [0.35929501 0.12636365 0.61400558 0.88485394]]


In [5]:
print(np.random.randn(4))

[ 0.78811449  0.57508336 -0.95759871 -0.86607101]


In [9]:
np.random.randint(0,10,5)

array([9, 1, 9, 5, 9])

In [10]:
np.sqrt(169)

np.float64(13.0)

In [12]:
ec=[1200,3400,2900,1800,2500].
energy_consuption=np.array(ec)
print("\nEnergy consuption (in Mwh for different rrenewable resources : ")
print(energy_consuption)


Energy consuption (in Mwh for different rrenewable resources : 
[1200 3400 2900 1800 2500]


In [14]:
b=np.ones(4)
a=np.ones((2,2))
print(f"{b}\n{a}")

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [16]:
c=np.zeros(8)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
identity_matrix=np.identity(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
total_consuption=np.sum(energy_consuption)
print(f"Total energy consuption :{total_consuption} Mwh")

Total energy consuption :11800 Mwh


In [27]:
mean_consuption=np.mean(energy_consuption)
print(f"Mean energy consuption :{mean_consuption:.2f}")

Mean energy consuption :2360.00


In [29]:
std_deviation=np.std(energy_consuption)
print(f"Standard deviation of energy consuption :{std_deviation:.2f} Mwh")

Standard deviation of energy consuption :781.28 Mwh


In [32]:
ec2=np.array([1200,3400,2900,1800,2500,1800])
# print(ec2)
print(f"Before reshaping:\n{ec2}")
reshaped_array=ec2.reshape(3,2)
print(f"After reshaping:\n{reshaped_array}")

Before reshaping:
[1200 3400 2900 1800 2500 1800]
After reshaping:
[[1200 3400]
 [2900 1800]
 [2500 1800]]


In [33]:
reshaped_array.flatten()

array([1200, 3400, 2900, 1800, 2500, 1800])

In [36]:
reshaped_array.T

array([[1200, 2900, 2500],
       [3400, 1800, 1800]])

In [37]:
resized_array=np.resize(ec2,(3,3))
print(resized_array)

[[1200 3400 2900]
 [1800 2500 1800]
 [1200 3400 2900]]
